.\" nroff source of ifacepref manpage
.\" alcortes@it.uc3m.es 2009-04-12
.\"
.\" groff -man ifacepref.4 | col -b > ifacepref_manpage.txt
.\" groff -man -Tps ifacepref.4 > ifacepref_manpage.ps
.\" groff -man -Tps ifacepref.4 | ps2pdf - - > ifacepref_manpage.pdf
.\" groff -man -Thtml ifacepref.4 > ifacepref_manpage.html
.\"
.TH IFACEPREF 4 2009-04-12 "Linux" "Linux Programmer's Manual"
.SH NAME
\fBifacepref\fP \- preferred network interface device
.SH DESCRIPTION
The character special file \fI/dev/ifacepref\fP provide
an interface to set and get the preferred network interface
card.
.LP
The preferred network interface device stores the name of
a network interface card. Privileged users can set the
preferred network interface at leisure. Users, applications and
other kernel modules can read the preferred network interface
as an input for its policies, routing decisions...
.SS Usage
Writting the name of the preferred iface to \fI/dev/ifacepref\fP
will make the device remember it. It can be changed afterwards by
aditional writes.
.LP
Network interface names are strings no longer than \fBIFNAMSIZ\fP
bytes. Any attempt to write more than \fBIFNAMSIZ\fP bytes in the
device will fail. Ifacepref dosen't ensure that the written data
is a real device or well formed interface name. The writer is
responsible of storing the ending '\\0' of the interface name.
.LP
The empty string is returned if there is no preferred interface.
.LP
Write operations are atomic: each write system call will set a
new preferred iface; don't try to splice a write between severall
system calls as any attempt to write at a non-zero offset
will fail.
.LP
Read operations don't need to be atomic. But as interface names are quite
small (16 bytes for most kernels), it is easy to read the whole device
in only one go.
.SS Polling
Writing to the device is always possible. Polling for read will return when
new content is available on the device.
.SS Configuration
If your system does not have
\fI/dev/ifacepref\fP created already, you will
have to create it by hand. It can be created with the following commands.
Major and minor numbers are dynamically
assigned by default when the module is loaded so you will need to
use \fBlsmod\fP to ask the system about them:

.nf
    ; lsmod | grep ifacepref
    ifacepref             254  0
    ; mknod /dev/ifacepref c 254 0
    ; chmod 664 /dev/ifacepref
    ; chown root:root /dev/ifacepref
.fi

.SH EXAMPLES
To set \fIeth0\fP as the preferred interface:

.nf
    ; echo -n -e "eth0\\0000" > /dev/ifacepref
.fi

To get the preferred interface:

.nf
    ; cat /dev/ifacepref ; echo
    eth0
.fi

To indicate there is no preferred interface:

.nf
    ; echo -n -e "\\0000" > /dev/ifacepref
.fi

.SH FILES
.I /dev/ifacepref
.SH BUGS
.LP
None known. Email the author if you find any.
.SH AUTHOR
Alberto Cortes <alcortes@it.uc3m.es>.
.SH "SEE ALSO"
\fBnetdevice\fP(7), \fBwrite\fP(2), \fBlsmod\fP(8)
